### ISSUE TITLE
Problem after adding package to config/app.php

### ISSUE THREAD

**Issue by wo01f** [baorv/cleverreach#2]
I run into this error when i try to use your package. 
This is from doing `composer dump-autoload` but the same error will also appear when i try to use your package in a Controller of mine.

```
 composer dump-autoload
Generating optimized autoload filesCarbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Warning:  Uncaught ErrorException: require(/home/viscompass/vendor/baorv/cleverreach/src/../cleverreach.php): failed to open stream: No such file or directory in /home/viscompass/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:59
Stack trace:
#0 /home/viscompass/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(59): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/viscompass/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(59): require()
#2 /home/viscompass/vendor/baorv/cleverreach/src/ServiceProvider.php(30): Illuminate\Support\ServiceProvider->mergeConfigFrom()
#3 /home/viscompass/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(598): Baorv\Cleverreach\ServiceProvider->register()
#4 /home/viscompass/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundation\Application->register()
#5 /home/viscompass/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illumi in /home/viscompass/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 59
PHP Fatal error:  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required '/home/viscompass/vendor/baorv/cleverreach/src/../cleverreach.php' (include_path='.:/usr/share/php') in /home/viscompass/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 59

In ServiceProvider.php line 59:

  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening requi
  red '/home/viscompass/vendor/baorv/cleverreach/src/../cleverreach.php' (inc
  lude_path='.:/usr/share/php')


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
```

**Comment by wo01f** [comment]
I fixed the error by changing your `ServiceProvider.php` in line **30** from

```php
        $this->mergeConfigFrom(__DIR__ . '/../cleverreach.php', 'cleverreach');

```
to
```php
        $this->mergeConfigFrom(__DIR__ . '/../config/cleverreach.php', 'cleverreach');

```
